######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 11 17:42:45 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arrowlcd.h pacer.h percent.h
SOURCES += arrowlcd.cpp main.cpp pacer.cpp percent.cpp
