######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 10 14:47:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arrowlcd.h
SOURCES += arrowlcd.cpp main.cpp
